openapi: 3.2.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /articles:
    get:
      summary: Get a list of articles
      tags: [Article]
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: "#/components/schemas/Summary"
                  limit:
                    type: number
                example:
                  limit: 3
                  articles:
                    - title: Sample 1
                      id: 1
                    - title: Sample 2
                      id: 2
                    - title: Sample 3
                      id: 3

  /articles/{id}:
    get:
      summary: Get one article with ID
      tags: [Article]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"

servers:
  - url: https://catcoder.com
    description: Stage Server
  - url: http://localhost:80/v1
    description: Dev Server

components:
  schemas:
    Summary:
      type: object
      properties:
        id:
          type: string
        title:
          type: string

    Article:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        content:
          type: string
          format: markdown
      example:
        id: "1"
        title: Sample 1
        author: tmori
        content:
          $ref: "./article.md"
