openapi: 3.2.0
info:
  title: Sample API
  version: 1.0.0
paths:
  /blogs:
    get:
      summary: Get a list of blogs
      tags: [Blogs]
      parameters:
        - name: search
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  blogs:
                    type: array
                    items:
                      $ref: "#/components/schemas/Summary"
                  limit:
                    type: number
                example:
                  blogs:
                    - title: Sample 1
                      id: 1
                    - title: Sample 2
                      id: 2
                    - title: Sample 3
                      id: 3

  /blogs/{id}:
    get:
      summary: Get one blog with ID
      tags: [Blog]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blog"

servers:
  - url: https://moritakuaki.com
    description: Stage Server
  - url: http://localhost:80/v1
    description: Dev Server

components:
  schemas:
    Summary:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        keywords:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            type: string

    Blog:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        author:
          type: string
        tags:
          type: array
          items:
            type: string
        createAt:
          type: string
          format: datetime
        updateAt:
          type: string
          format: datetime
          nullable: true
        content:
          type: string
          format: markdown
      example:
        id: "1"
        title: Sample 1
        author: tmori
        tags: [architecture, andorid]
        createAt: 2022-08-24T00:00:00Z+90:00
        updateAt: 2022-08-24T00:00:00Z+90:00
        content:
          $ref: "../blog/article.md"
