version: "3.1"
services:
  test_db:
    image: mysql:8
    restart: always
    hostname: test-sql
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_dev
    ports:
      - 3306:3306
volumes:
  db_volume:
