name: sample-action-on-push
run-name: ${{ github.actor }} is learning Github Actions
on:
  push:
    branches: ["main", "develop"]

env:
  AWS_REGION: ap-northeast-1
  S3_BUCKET: moritakuaki-teckblog
  PUSH_S3_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  contents: "read"
  id-token: "write"

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webpage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install & build
        run: |
          npm install
          npm install -g vite
          npm run build
      #- name: test
      #  run: npm run test
      - name: archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          # CAUTION:upload artifact don't use working-directory
          path: webpage/dist
          if-no-files-found: error

  deploy:
    name: Web Hosting
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: dist
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubMyRepo
          role-to-assume: ${{ env.PUSH_S3_ROLE_ARN }}
      - name: push to S3
        run: |
          aws s3 cp dist s3://${{ env.S3_BUCKET}} --recursive
