name: sample-action-on-push
run-name: ${{ github.actor }} is learning Github Actions
on: 
  push:
    branches: ["main","develop"]
jobs: 
  check-vite-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g vitest
      - run: vitest -v
