name: update-blogs
run-name: update blogs
on:
  push:
    branches: ["main"]
env:
  AWS_REGION: ap-northeast-1
  S3_BUCKET: takuaki-blog-content
  PUSH_S3_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
    
permissions:
  contents: "read"
  id-token: "write"

jobs:
  update:
    name: Update Blog
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: blog
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubCopyBlog
          role-to-assume: ${{ env.PUSH_S3_ROLE_ARN }}
      - name: update to s3
        run: |
          aws s3 sync blog s3://${{ env.S3_BUCKET }} --delete

        