name: update-blogs
run-name: update blogs
on:
  push:
    branches: ["develop"]
env:
  AWS_REGION: ap-northeast-1
  GITHUB_ACTION_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}

permissions:
  contents: "read"
  id-token: "write"

jobs:
  update:
    name: Update Blog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubCopyBlog
          role-to-assume: ${{ env.GITHUB_ACTION_ROLE_ARN }}
      - uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/tech-blog/buckets/blog-bucket"
          env_variable_name: "blog_bucket"
      - name: update to s3
        run: |
          aws s3 sync blog s3://${{ env.BLOG_BUCKET }} --delete
